name: build-docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1

    # Runs a single command using the runners shell
    - name: Run build-docker.sh
      run: ./build-docker.sh

    - name: Change to deploy directory
      run: cd deploy

    # Runs a set of commands using the runners shell
    - name: Check output
      uses: andstor/file-existence-action@v1
      with:
        files: "*PhotonVision.info, build.log, *PhotonVision.zip"
        allow_failure: true
        
    # Print output directory files
    - name: List output files
      run: ls -lh
      
    #
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-image
        path: |
          ./*PhotonVision.info
          ./build.log
          ./*PhotonVision.zip
